---
title: "exercise_01"
output: html_document
date: "2026-03-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1 (Probability Densities/ Expectations)

Nehmen wir folgende Wahrscheinlichkeitsdichtefunktion (probability density function PDF) an: $$f(x) = \begin{cases}c\cdot a \quad 0 \le x \le 1 \\ 0 \quad \quad \text{otherwise} \end{cases}$$

#### a) Wie groß ist der Wert der Konstante $c$?

Eine Grundregel für Dichtefunktionen ist, dass die Gesamtfläche unter der Kurve (das Integral) immer 1 sein muss.

Rechnerisch lässt sich dies also mit dem Integral für den gefragten Bereich lösen:
$$\int_0^1 c \cdot x \space dx = 1 \rightarrow c \cdot [\frac{x^2}{2}]_0^1 = 1 \rightarrow \frac{c}{2} = 1 \rightarrow c = 2$$

#### b)  Wie groß ist die Wahrscheinlichkeit, dass $x$ zwischen 0 und 0.5 liegt?

Rechnerisch lässt sich dies mit den Informationen von Aufgabe a durch das einsezten er Integralsgrenzen wie folgt lösen: $$\int_0^{0.5} 2x \space dx = [x^2]_0^{0.5} = 0.5^2 = 0.25$$

#### c)  Wie groß ist der Erwartungswert $E(X)$?

Der Erwartungswert ist der „Massenschwerpunkt“ (center-of-mass) der Verteilung.

Formel: $$E(X) = \int x \cdot f(x) \space dx$$ Rechnung: $$\int_0^1 x \cdot (2x)dx = \int_0^1 2x^2 \space dx = [\frac{2}{3} x^3]_0^1 = \frac{2}{3} \approx 0,667$$

#### d)  Wie groß ist der Erwartungswert $E(X^2)$?

Erwartungswert $E(X^2)$ (Optional)

Rechnung: $$\int_0^1 x^2 \cdot (2x) \space dx= \int_0^1 2x^3 \space dx = [\frac{2}{4} x4]_0^1 = \frac{2}{4} = 0,5$$
